apiVersion: v2
name: opencloud
description: OpenCloud Helm community chart
keywords:
  - opencloud
  - owncloud
  - ocis
maintainers:
  - name: Tim Herbert
    url: https://timherbert.de
type: application
version: 0.2.4
# renovate: datasource=docker depName=opencloudeu/opencloud-rolling
appVersion: latest
kubeVersion: ""
sources:
  - https://github.com/Tim-herbie/opencloud-helm
